### ISSUE TITLE
Fetch jobs for a player searched by name

### ISSUE THREAD

**Issue by kvahuja** [vainglorygame/apigrabber#11]
while we will pull all data, we need a way in case a player visits a site and wants to fetch/refresh his/her results. right now there is no way to do that.

There needs to be a way where we can register a job with crawljobs where we can register "fetch all matches for a player filter" and the workers can then fetch all matches for a player with most recent ones.

this job should only fetch last month (or 2) worth of matches. the Web/UI will have a way where User can ask to fetch more than that.

(future optimization)
this job can also be optimized such that if there are already some matches, it can create a job since that day..

**Comment by schneefux** [comment]
#39
