### ISSUE TITLE
Provide a way to trigger data-fetch for a player ID/Name

### ISSUE THREAD

**Issue by kvahuja** [vainglorygame/apigrabber#18]
this will be a case if a user starts a search and the data is not in our DB and we need to fetch the data. we will need:
1. create a job in Crawljobs with highest priority;
2. apigarbber should pick the job immediately and get data
3. processor should trigger only after apigrabber has done with fetch
4. Callback to Web to show the results

If we dont do this, we are running with a design that no matter who searches, the data is always in our DB. this needs discussion.

P.S.: genexp comfirmed that /player/{name} will be available soon. he also confirmed that /matches/filter by player is available now

**Comment by schneefux** [comment]
#39
