### ISSUE TITLE
LifetimeGold Units change after a certain value...

### ISSUE THREAD

**Issue by kvahuja** [vainglorygame/apigrabber#19]
Look at these 2 responses. notice how the level 2 player has a larger lifetimeGold value than the level 30 player. i presume the units are different for them. do we know what those units are and at what point do they change??

```JSON
{
  "shardId": "",
  "stats": {
    "played_ranked": 0,
    "winStreak": 1,
    "played": 0,
    "wins": 1,
    "level": 2,
    "lifetimeGold": 14194.75,
    "lossStreak": 0,
    "xp": 207
  },
  "name": "LighteningThief",
  "titleId": ""
}
```

```JSON
{
  "shardId": "",
  "stats": {
    "played_ranked": 319,
    "winStreak": 0,
    "played": 1404,
    "wins": 729,
    "level": 30,
    "lifetimeGold": 8876.875,
    "lossStreak": 2,
    "xp": 175450
  },
  "name": "StormCallerSr",
  "titleId": ""
}
```

**Comment by schneefux** [comment]
Confirmed buggy/broken on Vainglory API Discord

**Comment by kvahuja** [comment]
cool. opened https://github.com/madglory/gamelocker-vainglory/issues/56 for tracking.

**Comment by schneefux** [comment]
closing it here as it is not related to apigrabber implementation
