### ISSUE TITLE
Setup a server and run the apigrabber for at least 24 hours

### ISSUE THREAD

**Issue by kvahuja** [vainglorygame/apigrabber#21]
this is to stress test the service and ensure that it can run over long periods of time without error or fail. we will run this for one region and validate the data.

Will start once @schneefux gives the go ahead that service is ready.

**Comment by schneefux** [comment]
After https://github.com/vainglorygame/apigrabber/milestone/3 I'd consider Apigrabber ready for a test :)

**Comment by kvahuja** [comment]
awesome. so right now we have 5 open :) cant wait. meanwhile, i will setup server and get it all ready.

i dont think i am ready to put Docker in production just yet

**Comment by schneefux** [comment]
After recent events, https://github.com/vainglorygame/apigrabber/milestone/4 is the milestone "ready for testing"

**Comment by kvahuja** [comment]
ok cool. i will need your help on how to set this up on ubuntu. can you jot down the steps.

@schneefux

**Comment by schneefux** [comment]
done
