### ISSUE TITLE
Player table: some records get same data in attributes and relationships columns

### ISSUE THREAD

**Issue by kvahuja** [vainglorygame/apigrabber#26]
For some records data gets added into "relationships" column in the player table.

Run this query for SG shard and you will see that exact same data gets added to both columns.  API has the right data

```SQL
select * from player where attributes->>'name' in ('LighteningThief');
```

API call
```
https://api.dc01.gamelockerapp.com/shards/sg/players/6eab29f6-eed5-11e6-ba5f-068789513eb5
```

**Comment by schneefux** [comment]
Probably gone after the rewrite #36, if not, reopen.
