### ISSUE TITLE
logging ....?

### ISSUE THREAD

**Issue by kvahuja** [vainglorygame/apigrabber#4]
Can we put in some debug/info logs for the crawler? something that allows us to debug and see if jobs have passed or failed with whatever error?

**Comment by schneefux** [comment]
Logs are currently printed on the console, running docker-compose without `-d` shows them.
I use the Python `logging` library (https://docs.python.org/3.6/howto/logging.html), it can log to files too. Where should the logs be saved?

**Comment by kvahuja** [comment]
put them in /var/logs/apigrabber/* and /var/logs/processor/*

I will setup logrotate at OS level and maybe pull them into ELK and get rid of files (eventually).

**Comment by schneefux** [comment]
done in 15df7d751e6cb59d3162c8fdc0faa983de67b73c

logs are saved into `logs/apigrabber.log` or `logs/processor.log` etc., is that okay? I don't want to hard code an absolute path like /var/logs…
File logs are written with level debug or higher, console logs are warning level or higher.
