### ISSUE TITLE
Cleanup branches...

### ISSUE THREAD

**Issue by kvahuja** [vainglorygame/apigrabber#52]
* delete all feature branches that have been merged
* setup develop branch to be the branch where code is being written during development
* master will be used for production deployments

**Comment by schneefux** [comment]
Deleting merged branches from remote:
`git branch -r --merged | grep -v "(^\*|master|dev)" | sed 's/origin\//:/' | xargs -n 1 git push origin`
Deleting merged branches from local:
`git branch --merged | egrep -v "(^\*|master|dev)" | xargs git branch -d`

Done :)
