### ISSUE TITLE
Log player name or id with the info logs

### ISSUE THREAD

**Issue by kvahuja** [vainglorygame/apigrabber#59]
This is to trace and help us test and debug in production.
 
(also these should be info not debug)

i searched a new player and see following
```
DEBUG:root:705: inserted 29 matches from API into database
DEBUG:root:705: inserted 42 matches from API into database
DEBUG:root:705: inserted 45 matches from API into database
```

no clue how may were primary and when the spider fired

**Comment by schneefux** [comment]
60cb876 done
