### ISSUE TITLE
setting up new crawljobs

### ISSUE THREAD

**Issue by kvahuja** [vainglorygame/apigrabber#6]
I presume that there is a process that reads the existing data in "Crawljobs" and based on last entry will create new entries into the table. It goes back 1/4 hr in case something was missed. this has a potential leaking issue:

1. If the API endpoint was delayed then any jobs that were processed will not fetch any data
2. if we go beyond the limit, we will never be able to fetch the data

So the "start time" for new jobs to be created should **NOT BE** based on the last crawljob time, but the last record we entered in our match table. we need to see if API gives is any "time" and we use that. if it doesnt then we need to find the same based on "the job parameter when we pulled the data.

**Comment by schneefux** [comment]
#39
