### ISSUE TITLE
Better Logging

### ISSUE THREAD

**Issue by kvahuja** [vainglorygame/apigrabber#61]
when we get
```
WARNING:root:API returned error: '[{'title': 'Not Found'}]'
WARNING:root:batch failed, reset
```

we need to log the Query we sent so that we can later on see if it was our code or API or just a wrong search

again spider gave  - should not happen. i cant really debug
```
WARNING:root:API returned error: '[{'title': 'Not Found'}]'
WARNING:root:batch failed, reset
```

**Comment by schneefux** [comment]
"API returned error: ..." is saved in jobs.payload->error and the job is set to "failed".
The API will return more useful responses "soon".

**Comment by schneefux** [comment]
9cfc1067fdd607de73327d65d44a6bbae90e9469 done
