### ISSUE TITLE
improvement to CrawlJobs

### ISSUE THREAD

**Issue by kvahuja** [vainglorygame/apigrabber#7]
The current setup of Entering a job in DB and then workers reading it is awesome. not in Release 1.0, but later we can use this to enable some advanced techniques to sync our data. For now, I suggest we add the following columns to the table which we may not use now.

- [ ] **Priority**: a simple integer where 1 is the highest priority. this way when workers fetch the jobs they should do ORDER BY priority and process accordingly. this will be helpful because we can queue jobs and workers will deal with them automatically without us worrying
- [ ] **Query**: this is in some shape and forms the query or endpoint that we will fire. this is an indication for workers what to fetch. let's say we want to sync everything for a user for last 2 months. we can simply set up a job and worker will pick it up and fire the query and do a sync.
- [ ] **Status**: this can quickly us if a job was successful or did it have errors. we can then log the errors and put this ID in for debugging
- [ ] **Records processed:** a simple count of how many matches were processed. may help us later

Expose this list via a webtool (we can use the PHP layer to query and show the results under admin. this will be a great way for us to administer what all is pending as we go into production. @schneefux - makes sense? I can convert this to a story in vainsovial.com's admin panel..

**Comment by schneefux** [comment]
#38
